apiVersion: v1
kind: Service
metadata:
  name: user-request-service
spec:
  type: NodePort
  ports:
    - name: "8003"
      port: 8003
      targetPort: 8003
  selector:
    io.kompose.service: user-request-service
