# Image préexistante optimisée pour Python et FastAPI
FROM tiangolo/uvicorn-gunicorn-fastapi:python3.9

# Installer uniquement les bibliothèques supplémentaires nécessaires
RUN pip install --no-cache-dir requests

# Copier le fichier du service
COPY user_request_service.py /app/
WORKDIR /app

# Exposer le port 8003
EXPOSE 8003

# Commande de démarrage
CMD ["uvicorn", "user_request_service:app", "--host", "0.0.0.0", "--port", "8003"]
