apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Users\minhe\Documents\Cours\DataScale\Cloud\kompose.exe convert
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: retrieval-service
  name: retrieval-service
spec:
  ports:
    - name: "8001"
      port: 8001
      targetPort: 8001
  selector:
    io.kompose.service: retrieval-service
